sudo: required
# above sudo is required for the following tasks
services:
  - docker


before_install:
  - docker build -t asadmehmoodch/frontend -f Dockerfile.dev .

script:
  - docker run asadmehmoodch/frontend npm run test -- --coverage
